apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: eicarserver
  labels:
    app: eicarserver
spec:
  type: NodePort
  ports:
  - port: 80
    name: eicarserver
    targetPort: 80
    nodePort: 32756
  selector:
    app: eicarserver
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eicarserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eicarserver
    spec:
      containers:
      - name: eicarserver
        image: mawinkler/eicarserver:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
